Resources:
  ### This role is used by the CodeDeploy Deployment Group so it can access the necessary AWS APIs for pinpointing which servers to deploy to
  CodeDeploySerivceRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: DevopsMWDemoCodeDeployServiceRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  ### This role is used by the QA & Prod EC2 instances in cloudformation-environment.yaml so that they're able to access the code bundles to be deployed
  CodeDeployEC2Role:
    Type: AWS::IAM::Role
    Properties: 
      RoleName: DevopsMWDemoEC2Role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: "root"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action:
                  - "s3:Get*"
                  - "s3:List*"
                Resource:
                  - "arn:aws:s3:::codepipeline-us-east-*"
                  - "arn:aws:s3:::codepipeline-us-west-*"

  ### This is an "add-on" to the role above for the QA & Prod servers to be able to bind the permissions
  CodeDeployEC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - Ref: "CodeDeployEC2Role"
      InstanceProfileName: DevopsMWDemoInstanceProfile